services:
  web:
    container_name: '${COMPOSE_PROJECT_NAME}_web'
    restart: always
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL?err}
    env_file:
      - .env
    ports:
      - "${PORT:-3333}:3333"
    networks:
      - sail
    depends_on:
      - pgsql
      - redis
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3333}
      HOST: ${HOST:-0.0.0.0}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      APP_KEY: ${APP_KEY?err}
      SESSION_DRIVER: ${SESSION_DRIVER:-cookie}
      DRIVE_DISK: ${DRIVE_DISK:-fs}
      LIMITER_STORE: ${LIMITER_STORE:-database}
      DB_HOST: ${DB_HOST:-pgsql}
      DB_PORT: 5432
      DB_USER: ${DB_USER?err}
      DB_PASSWORD: ${DB_PASSWORD?err}
      DB_DATABASE: ${DB_DATABASE?err}
      VITE_API_URL: ${VITE_API_URL?err}
      APP_NAME: ${APP_NAME:-Exprefrei}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      APP_ENV: ${APP_ENV:-production}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      # CORRECTION ICI : On mappe directement le dossier tmp
      - 'web_uploads:/app/apps/web/build/tmp'

  pgsql:
    image: 'pgvector/pgvector:0.8.0-pg17'
    container_name: '${COMPOSE_PROJECT_NAME}_pgsql'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-default}'
      POSTGRES_USER: '${DB_USER?:err}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-default}', '-U', '${DB_USER}' ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:7-alpine'
    container_name: '${COMPOSE_PROJECT_NAME}_redis'
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      sh -c "if [ -n \"$$REDIS_PASSWORD\" ]; then redis-server --requirepass $$REDIS_PASSWORD; else redis-server; fi"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

  cloudflared-exprefrei:
    image: cloudflare/cloudflared:latest
    container_name: '${COMPOSE_PROJECT_NAME}_cf'
    command: tunnel run --token ${CF_TOKEN}
    networks:
      - sail
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: always

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
  sailredis:
  web_uploads: # Ne pas oubli